USE [master]
GO
/****** Object:  Database [NASA]    Script Date: 12/5/2024 12:58:11 AM ******/
CREATE DATABASE [NASA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NASA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NASA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NASA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NASA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [NASA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NASA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NASA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NASA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NASA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NASA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NASA] SET ARITHABORT OFF 
GO
ALTER DATABASE [NASA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NASA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NASA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NASA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NASA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NASA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NASA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NASA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NASA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NASA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [NASA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NASA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NASA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NASA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NASA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NASA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NASA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NASA] SET RECOVERY FULL 
GO
ALTER DATABASE [NASA] SET  MULTI_USER 
GO
ALTER DATABASE [NASA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NASA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NASA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NASA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NASA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NASA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'NASA', N'ON'
GO
ALTER DATABASE [NASA] SET QUERY_STORE = ON
GO
ALTER DATABASE [NASA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [NASA]
GO
/****** Object:  Table [dbo].[SearchHistories]    Script Date: 12/5/2024 12:58:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SearchHistories](
	[SearchId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[SearchTerm] [nvarchar](255) NOT NULL,
	[SearchDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[SearchId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 12/5/2024 12:58:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
	[FullName] [nvarchar](100) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([UserId], [Email], [PasswordHash], [FullName], [CreatedAt]) VALUES (1, N'thapabinshila@gmail.com', N'AQAAAAIAAYagAAAAELD29ZsqtJ0WP4V/NoOBjoRLJaF/N3/sTSFZmiRJPgO/2H8n9HgHbQIJMV8n32VYFw==', N'Binshila', CAST(N'2024-12-05T00:20:27.847' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Users__A9D10534AC9D0894]    Script Date: 12/5/2024 12:58:12 AM ******/
ALTER TABLE [dbo].[Users] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SearchHistories] ADD  DEFAULT (getdate()) FOR [SearchDate]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[SearchHistories]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON DELETE CASCADE
GO
USE [master]
GO
ALTER DATABASE [NASA] SET  READ_WRITE 
GO
